/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the PagingInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagingInformation{}

// PagingInformation Information provided in paged collection query responses, only when the response is partial, meaning that not all queried instances are returned. The return code will be 206 when this is returned.
type PagingInformation struct {
	// The number of instances in the complete queried collection (not just the size of the current response). If the request was filtered, then this is the size of the complete filtered collection.
	TotalInstances *int32 `json:"total_instances,omitempty"`
	// The URL to fetch the first page of this collection (including filtering and sorting parameters).
	First *string `json:"first,omitempty"`
	// The URL to fetch the last page of this collection (including filtering and sorting parameters).
	Last *string `json:"last,omitempty"`
	// The URL to fetch the next page of this collection (including filtering and sorting parameters). This will not be returned with the last page of a collection.
	Next *string `json:"next,omitempty"`
	// The URL to fetch the previous page of this collection (including filtering and sorting parameters). This will not be returned with the first page of a collection.
	Prev *string `json:"prev,omitempty"`
}

// NewPagingInformation instantiates a new PagingInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagingInformation() *PagingInformation {
	this := PagingInformation{}
	return &this
}

// NewPagingInformationWithDefaults instantiates a new PagingInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagingInformationWithDefaults() *PagingInformation {
	this := PagingInformation{}
	return &this
}

// GetTotalInstances returns the TotalInstances field value if set, zero value otherwise.
func (o *PagingInformation) GetTotalInstances() int32 {
	if o == nil || IsNil(o.TotalInstances) {
		var ret int32
		return ret
	}
	return *o.TotalInstances
}

// GetTotalInstancesOk returns a tuple with the TotalInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingInformation) GetTotalInstancesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalInstances) {
		return nil, false
	}
	return o.TotalInstances, true
}

// HasTotalInstances returns a boolean if a field has been set.
func (o *PagingInformation) HasTotalInstances() bool {
	if o != nil && !IsNil(o.TotalInstances) {
		return true
	}

	return false
}

// SetTotalInstances gets a reference to the given int32 and assigns it to the TotalInstances field.
func (o *PagingInformation) SetTotalInstances(v int32) {
	o.TotalInstances = &v
}

// GetFirst returns the First field value if set, zero value otherwise.
func (o *PagingInformation) GetFirst() string {
	if o == nil || IsNil(o.First) {
		var ret string
		return ret
	}
	return *o.First
}

// GetFirstOk returns a tuple with the First field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingInformation) GetFirstOk() (*string, bool) {
	if o == nil || IsNil(o.First) {
		return nil, false
	}
	return o.First, true
}

// HasFirst returns a boolean if a field has been set.
func (o *PagingInformation) HasFirst() bool {
	if o != nil && !IsNil(o.First) {
		return true
	}

	return false
}

// SetFirst gets a reference to the given string and assigns it to the First field.
func (o *PagingInformation) SetFirst(v string) {
	o.First = &v
}

// GetLast returns the Last field value if set, zero value otherwise.
func (o *PagingInformation) GetLast() string {
	if o == nil || IsNil(o.Last) {
		var ret string
		return ret
	}
	return *o.Last
}

// GetLastOk returns a tuple with the Last field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingInformation) GetLastOk() (*string, bool) {
	if o == nil || IsNil(o.Last) {
		return nil, false
	}
	return o.Last, true
}

// HasLast returns a boolean if a field has been set.
func (o *PagingInformation) HasLast() bool {
	if o != nil && !IsNil(o.Last) {
		return true
	}

	return false
}

// SetLast gets a reference to the given string and assigns it to the Last field.
func (o *PagingInformation) SetLast(v string) {
	o.Last = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PagingInformation) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingInformation) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PagingInformation) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PagingInformation) SetNext(v string) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *PagingInformation) GetPrev() string {
	if o == nil || IsNil(o.Prev) {
		var ret string
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagingInformation) GetPrevOk() (*string, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *PagingInformation) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given string and assigns it to the Prev field.
func (o *PagingInformation) SetPrev(v string) {
	o.Prev = &v
}

func (o PagingInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagingInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalInstances) {
		toSerialize["total_instances"] = o.TotalInstances
	}
	if !IsNil(o.First) {
		toSerialize["first"] = o.First
	}
	if !IsNil(o.Last) {
		toSerialize["last"] = o.Last
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	return toSerialize, nil
}

type NullablePagingInformation struct {
	value *PagingInformation
	isSet bool
}

func (v NullablePagingInformation) Get() *PagingInformation {
	return v.value
}

func (v *NullablePagingInformation) Set(val *PagingInformation) {
	v.value = val
	v.isSet = true
}

func (v NullablePagingInformation) IsSet() bool {
	return v.isSet
}

func (v *NullablePagingInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagingInformation(val *PagingInformation) *NullablePagingInformation {
	return &NullablePagingInformation{value: val, isSet: true}
}

func (v NullablePagingInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagingInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


