/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the AwsTrustPolicyStatementInnerPrincipal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsTrustPolicyStatementInnerPrincipal{}

// AwsTrustPolicyStatementInnerPrincipal struct for AwsTrustPolicyStatementInnerPrincipal
type AwsTrustPolicyStatementInnerPrincipal struct {
	AWS *string `json:"AWS,omitempty"`
}

// NewAwsTrustPolicyStatementInnerPrincipal instantiates a new AwsTrustPolicyStatementInnerPrincipal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsTrustPolicyStatementInnerPrincipal() *AwsTrustPolicyStatementInnerPrincipal {
	this := AwsTrustPolicyStatementInnerPrincipal{}
	return &this
}

// NewAwsTrustPolicyStatementInnerPrincipalWithDefaults instantiates a new AwsTrustPolicyStatementInnerPrincipal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsTrustPolicyStatementInnerPrincipalWithDefaults() *AwsTrustPolicyStatementInnerPrincipal {
	this := AwsTrustPolicyStatementInnerPrincipal{}
	return &this
}

// GetAWS returns the AWS field value if set, zero value otherwise.
func (o *AwsTrustPolicyStatementInnerPrincipal) GetAWS() string {
	if o == nil || IsNil(o.AWS) {
		var ret string
		return ret
	}
	return *o.AWS
}

// GetAWSOk returns a tuple with the AWS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsTrustPolicyStatementInnerPrincipal) GetAWSOk() (*string, bool) {
	if o == nil || IsNil(o.AWS) {
		return nil, false
	}
	return o.AWS, true
}

// HasAWS returns a boolean if a field has been set.
func (o *AwsTrustPolicyStatementInnerPrincipal) HasAWS() bool {
	if o != nil && !IsNil(o.AWS) {
		return true
	}

	return false
}

// SetAWS gets a reference to the given string and assigns it to the AWS field.
func (o *AwsTrustPolicyStatementInnerPrincipal) SetAWS(v string) {
	o.AWS = &v
}

func (o AwsTrustPolicyStatementInnerPrincipal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsTrustPolicyStatementInnerPrincipal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AWS) {
		toSerialize["AWS"] = o.AWS
	}
	return toSerialize, nil
}

type NullableAwsTrustPolicyStatementInnerPrincipal struct {
	value *AwsTrustPolicyStatementInnerPrincipal
	isSet bool
}

func (v NullableAwsTrustPolicyStatementInnerPrincipal) Get() *AwsTrustPolicyStatementInnerPrincipal {
	return v.value
}

func (v *NullableAwsTrustPolicyStatementInnerPrincipal) Set(val *AwsTrustPolicyStatementInnerPrincipal) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsTrustPolicyStatementInnerPrincipal) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsTrustPolicyStatementInnerPrincipal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsTrustPolicyStatementInnerPrincipal(val *AwsTrustPolicyStatementInnerPrincipal) *NullableAwsTrustPolicyStatementInnerPrincipal {
	return &NullableAwsTrustPolicyStatementInnerPrincipal{value: val, isSet: true}
}

func (v NullableAwsTrustPolicyStatementInnerPrincipal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsTrustPolicyStatementInnerPrincipal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


