/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the LicensesCollection206Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LicensesCollection206Response{}

// LicensesCollection206Response struct for LicensesCollection206Response
type LicensesCollection206Response struct {
	Paging *PagingInformation `json:"paging,omitempty"`
	Results []LicensesInstance `json:"results,omitempty"`
}

// NewLicensesCollection206Response instantiates a new LicensesCollection206Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLicensesCollection206Response() *LicensesCollection206Response {
	this := LicensesCollection206Response{}
	return &this
}

// NewLicensesCollection206ResponseWithDefaults instantiates a new LicensesCollection206Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLicensesCollection206ResponseWithDefaults() *LicensesCollection206Response {
	this := LicensesCollection206Response{}
	return &this
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *LicensesCollection206Response) GetPaging() PagingInformation {
	if o == nil || IsNil(o.Paging) {
		var ret PagingInformation
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LicensesCollection206Response) GetPagingOk() (*PagingInformation, bool) {
	if o == nil || IsNil(o.Paging) {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *LicensesCollection206Response) HasPaging() bool {
	if o != nil && !IsNil(o.Paging) {
		return true
	}

	return false
}

// SetPaging gets a reference to the given PagingInformation and assigns it to the Paging field.
func (o *LicensesCollection206Response) SetPaging(v PagingInformation) {
	o.Paging = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *LicensesCollection206Response) GetResults() []LicensesInstance {
	if o == nil || IsNil(o.Results) {
		var ret []LicensesInstance
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LicensesCollection206Response) GetResultsOk() ([]LicensesInstance, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *LicensesCollection206Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []LicensesInstance and assigns it to the Results field.
func (o *LicensesCollection206Response) SetResults(v []LicensesInstance) {
	o.Results = v
}

func (o LicensesCollection206Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LicensesCollection206Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Paging) {
		toSerialize["paging"] = o.Paging
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableLicensesCollection206Response struct {
	value *LicensesCollection206Response
	isSet bool
}

func (v NullableLicensesCollection206Response) Get() *LicensesCollection206Response {
	return v.value
}

func (v *NullableLicensesCollection206Response) Set(val *LicensesCollection206Response) {
	v.value = val
	v.isSet = true
}

func (v NullableLicensesCollection206Response) IsSet() bool {
	return v.isSet
}

func (v *NullableLicensesCollection206Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLicensesCollection206Response(val *LicensesCollection206Response) *NullableLicensesCollection206Response {
	return &NullableLicensesCollection206Response{value: val, isSet: true}
}

func (v NullableLicensesCollection206Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLicensesCollection206Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


