/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the SystemOnPremDeploymentDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemOnPremDeploymentDetails{}

// SystemOnPremDeploymentDetails On-premise deployment details.
type SystemOnPremDeploymentDetails struct {
	DeploymentType *SystemDeploymentTypeEnum `json:"deployment_type,omitempty"`
	// Name of the site where the system is located.
	SiteName *string `json:"site_name,omitempty"`
	// User provided description of where the system is located.
	Location *string `json:"location,omitempty"`
	// Name of the country where the system is located.
	Country *string `json:"country,omitempty"`
	// Name of the state where the system is located.
	State *string `json:"state,omitempty"`
	// Name of the city where the system is located.
	City *string `json:"city,omitempty"`
	// Street address 1 of where the system is located.
	StreetAddress1 *string `json:"street_address_1,omitempty"`
	// Street address 2 of where the system is located.
	StreetAddress2 *string `json:"street_address_2,omitempty"`
	// State ZIP code of where the system is located.
	ZipCode *string `json:"zip_code,omitempty"`
}

// NewSystemOnPremDeploymentDetails instantiates a new SystemOnPremDeploymentDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemOnPremDeploymentDetails() *SystemOnPremDeploymentDetails {
	this := SystemOnPremDeploymentDetails{}
	var deploymentType SystemDeploymentTypeEnum = SYSTEMDEPLOYMENTTYPEENUM_ONPREM
	this.DeploymentType = &deploymentType
	return &this
}

// NewSystemOnPremDeploymentDetailsWithDefaults instantiates a new SystemOnPremDeploymentDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemOnPremDeploymentDetailsWithDefaults() *SystemOnPremDeploymentDetails {
	this := SystemOnPremDeploymentDetails{}
	var deploymentType SystemDeploymentTypeEnum = SYSTEMDEPLOYMENTTYPEENUM_ONPREM
	this.DeploymentType = &deploymentType
	return &this
}

// GetDeploymentType returns the DeploymentType field value if set, zero value otherwise.
func (o *SystemOnPremDeploymentDetails) GetDeploymentType() SystemDeploymentTypeEnum {
	if o == nil || IsNil(o.DeploymentType) {
		var ret SystemDeploymentTypeEnum
		return ret
	}
	return *o.DeploymentType
}

// GetDeploymentTypeOk returns a tuple with the DeploymentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemOnPremDeploymentDetails) GetDeploymentTypeOk() (*SystemDeploymentTypeEnum, bool) {
	if o == nil || IsNil(o.DeploymentType) {
		return nil, false
	}
	return o.DeploymentType, true
}

// HasDeploymentType returns a boolean if a field has been set.
func (o *SystemOnPremDeploymentDetails) HasDeploymentType() bool {
	if o != nil && !IsNil(o.DeploymentType) {
		return true
	}

	return false
}

// SetDeploymentType gets a reference to the given SystemDeploymentTypeEnum and assigns it to the DeploymentType field.
func (o *SystemOnPremDeploymentDetails) SetDeploymentType(v SystemDeploymentTypeEnum) {
	o.DeploymentType = &v
}

// GetSiteName returns the SiteName field value if set, zero value otherwise.
func (o *SystemOnPremDeploymentDetails) GetSiteName() string {
	if o == nil || IsNil(o.SiteName) {
		var ret string
		return ret
	}
	return *o.SiteName
}

// GetSiteNameOk returns a tuple with the SiteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemOnPremDeploymentDetails) GetSiteNameOk() (*string, bool) {
	if o == nil || IsNil(o.SiteName) {
		return nil, false
	}
	return o.SiteName, true
}

// HasSiteName returns a boolean if a field has been set.
func (o *SystemOnPremDeploymentDetails) HasSiteName() bool {
	if o != nil && !IsNil(o.SiteName) {
		return true
	}

	return false
}

// SetSiteName gets a reference to the given string and assigns it to the SiteName field.
func (o *SystemOnPremDeploymentDetails) SetSiteName(v string) {
	o.SiteName = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *SystemOnPremDeploymentDetails) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemOnPremDeploymentDetails) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *SystemOnPremDeploymentDetails) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *SystemOnPremDeploymentDetails) SetLocation(v string) {
	o.Location = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *SystemOnPremDeploymentDetails) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemOnPremDeploymentDetails) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *SystemOnPremDeploymentDetails) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *SystemOnPremDeploymentDetails) SetCountry(v string) {
	o.Country = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *SystemOnPremDeploymentDetails) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemOnPremDeploymentDetails) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *SystemOnPremDeploymentDetails) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *SystemOnPremDeploymentDetails) SetState(v string) {
	o.State = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *SystemOnPremDeploymentDetails) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemOnPremDeploymentDetails) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *SystemOnPremDeploymentDetails) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *SystemOnPremDeploymentDetails) SetCity(v string) {
	o.City = &v
}

// GetStreetAddress1 returns the StreetAddress1 field value if set, zero value otherwise.
func (o *SystemOnPremDeploymentDetails) GetStreetAddress1() string {
	if o == nil || IsNil(o.StreetAddress1) {
		var ret string
		return ret
	}
	return *o.StreetAddress1
}

// GetStreetAddress1Ok returns a tuple with the StreetAddress1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemOnPremDeploymentDetails) GetStreetAddress1Ok() (*string, bool) {
	if o == nil || IsNil(o.StreetAddress1) {
		return nil, false
	}
	return o.StreetAddress1, true
}

// HasStreetAddress1 returns a boolean if a field has been set.
func (o *SystemOnPremDeploymentDetails) HasStreetAddress1() bool {
	if o != nil && !IsNil(o.StreetAddress1) {
		return true
	}

	return false
}

// SetStreetAddress1 gets a reference to the given string and assigns it to the StreetAddress1 field.
func (o *SystemOnPremDeploymentDetails) SetStreetAddress1(v string) {
	o.StreetAddress1 = &v
}

// GetStreetAddress2 returns the StreetAddress2 field value if set, zero value otherwise.
func (o *SystemOnPremDeploymentDetails) GetStreetAddress2() string {
	if o == nil || IsNil(o.StreetAddress2) {
		var ret string
		return ret
	}
	return *o.StreetAddress2
}

// GetStreetAddress2Ok returns a tuple with the StreetAddress2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemOnPremDeploymentDetails) GetStreetAddress2Ok() (*string, bool) {
	if o == nil || IsNil(o.StreetAddress2) {
		return nil, false
	}
	return o.StreetAddress2, true
}

// HasStreetAddress2 returns a boolean if a field has been set.
func (o *SystemOnPremDeploymentDetails) HasStreetAddress2() bool {
	if o != nil && !IsNil(o.StreetAddress2) {
		return true
	}

	return false
}

// SetStreetAddress2 gets a reference to the given string and assigns it to the StreetAddress2 field.
func (o *SystemOnPremDeploymentDetails) SetStreetAddress2(v string) {
	o.StreetAddress2 = &v
}

// GetZipCode returns the ZipCode field value if set, zero value otherwise.
func (o *SystemOnPremDeploymentDetails) GetZipCode() string {
	if o == nil || IsNil(o.ZipCode) {
		var ret string
		return ret
	}
	return *o.ZipCode
}

// GetZipCodeOk returns a tuple with the ZipCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemOnPremDeploymentDetails) GetZipCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ZipCode) {
		return nil, false
	}
	return o.ZipCode, true
}

// HasZipCode returns a boolean if a field has been set.
func (o *SystemOnPremDeploymentDetails) HasZipCode() bool {
	if o != nil && !IsNil(o.ZipCode) {
		return true
	}

	return false
}

// SetZipCode gets a reference to the given string and assigns it to the ZipCode field.
func (o *SystemOnPremDeploymentDetails) SetZipCode(v string) {
	o.ZipCode = &v
}

func (o SystemOnPremDeploymentDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemOnPremDeploymentDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeploymentType) {
		toSerialize["deployment_type"] = o.DeploymentType
	}
	if !IsNil(o.SiteName) {
		toSerialize["site_name"] = o.SiteName
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.StreetAddress1) {
		toSerialize["street_address_1"] = o.StreetAddress1
	}
	if !IsNil(o.StreetAddress2) {
		toSerialize["street_address_2"] = o.StreetAddress2
	}
	if !IsNil(o.ZipCode) {
		toSerialize["zip_code"] = o.ZipCode
	}
	return toSerialize, nil
}

type NullableSystemOnPremDeploymentDetails struct {
	value *SystemOnPremDeploymentDetails
	isSet bool
}

func (v NullableSystemOnPremDeploymentDetails) Get() *SystemOnPremDeploymentDetails {
	return v.value
}

func (v *NullableSystemOnPremDeploymentDetails) Set(val *SystemOnPremDeploymentDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemOnPremDeploymentDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemOnPremDeploymentDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemOnPremDeploymentDetails(val *SystemOnPremDeploymentDetails) *NullableSystemOnPremDeploymentDetails {
	return &NullableSystemOnPremDeploymentDetails{value: val, isSet: true}
}

func (v NullableSystemOnPremDeploymentDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemOnPremDeploymentDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


