/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the StorageProductsCollection200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageProductsCollection200Response{}

// StorageProductsCollection200Response struct for StorageProductsCollection200Response
type StorageProductsCollection200Response struct {
	Results []StorageProductsInstance `json:"results,omitempty"`
	Paging *PagingInformation `json:"paging,omitempty"`
}

// NewStorageProductsCollection200Response instantiates a new StorageProductsCollection200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageProductsCollection200Response() *StorageProductsCollection200Response {
	this := StorageProductsCollection200Response{}
	return &this
}

// NewStorageProductsCollection200ResponseWithDefaults instantiates a new StorageProductsCollection200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageProductsCollection200ResponseWithDefaults() *StorageProductsCollection200Response {
	this := StorageProductsCollection200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *StorageProductsCollection200Response) GetResults() []StorageProductsInstance {
	if o == nil || IsNil(o.Results) {
		var ret []StorageProductsInstance
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageProductsCollection200Response) GetResultsOk() ([]StorageProductsInstance, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *StorageProductsCollection200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []StorageProductsInstance and assigns it to the Results field.
func (o *StorageProductsCollection200Response) SetResults(v []StorageProductsInstance) {
	o.Results = v
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *StorageProductsCollection200Response) GetPaging() PagingInformation {
	if o == nil || IsNil(o.Paging) {
		var ret PagingInformation
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageProductsCollection200Response) GetPagingOk() (*PagingInformation, bool) {
	if o == nil || IsNil(o.Paging) {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *StorageProductsCollection200Response) HasPaging() bool {
	if o != nil && !IsNil(o.Paging) {
		return true
	}

	return false
}

// SetPaging gets a reference to the given PagingInformation and assigns it to the Paging field.
func (o *StorageProductsCollection200Response) SetPaging(v PagingInformation) {
	o.Paging = &v
}

func (o StorageProductsCollection200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageProductsCollection200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Paging) {
		toSerialize["paging"] = o.Paging
	}
	return toSerialize, nil
}

type NullableStorageProductsCollection200Response struct {
	value *StorageProductsCollection200Response
	isSet bool
}

func (v NullableStorageProductsCollection200Response) Get() *StorageProductsCollection200Response {
	return v.value
}

func (v *NullableStorageProductsCollection200Response) Set(val *StorageProductsCollection200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageProductsCollection200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageProductsCollection200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageProductsCollection200Response(val *StorageProductsCollection200Response) *NullableStorageProductsCollection200Response {
	return &NullableStorageProductsCollection200Response{value: val, isSet: true}
}

func (v NullableStorageProductsCollection200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageProductsCollection200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


