/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MultiselectFreetextOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultiselectFreetextOption{}

// MultiselectFreetextOption Model for providing multi select option
type MultiselectFreetextOption struct {
	// Display name of the option
	Name string `json:"name"`
	// Description of the option
	Description string `json:"description"`
	// All the available values for the option
	AvailableOptions []string `json:"available_options"`
	// Is it mandatory
	IsConfigurable bool `json:"is_configurable"`
	// Type of the option
	Type string `json:"type"`
}

type _MultiselectFreetextOption MultiselectFreetextOption

// NewMultiselectFreetextOption instantiates a new MultiselectFreetextOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiselectFreetextOption(name string, description string, availableOptions []string, isConfigurable bool, type_ string) *MultiselectFreetextOption {
	this := MultiselectFreetextOption{}
	this.Name = name
	this.Description = description
	this.AvailableOptions = availableOptions
	this.IsConfigurable = isConfigurable
	this.Type = type_
	return &this
}

// NewMultiselectFreetextOptionWithDefaults instantiates a new MultiselectFreetextOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiselectFreetextOptionWithDefaults() *MultiselectFreetextOption {
	this := MultiselectFreetextOption{}
	var type_ string = "MULTISELECT_FREETEXT"
	this.Type = type_
	return &this
}

// GetName returns the Name field value
func (o *MultiselectFreetextOption) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MultiselectFreetextOption) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MultiselectFreetextOption) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *MultiselectFreetextOption) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *MultiselectFreetextOption) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *MultiselectFreetextOption) SetDescription(v string) {
	o.Description = v
}

// GetAvailableOptions returns the AvailableOptions field value
func (o *MultiselectFreetextOption) GetAvailableOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AvailableOptions
}

// GetAvailableOptionsOk returns a tuple with the AvailableOptions field value
// and a boolean to check if the value has been set.
func (o *MultiselectFreetextOption) GetAvailableOptionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvailableOptions, true
}

// SetAvailableOptions sets field value
func (o *MultiselectFreetextOption) SetAvailableOptions(v []string) {
	o.AvailableOptions = v
}

// GetIsConfigurable returns the IsConfigurable field value
func (o *MultiselectFreetextOption) GetIsConfigurable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsConfigurable
}

// GetIsConfigurableOk returns a tuple with the IsConfigurable field value
// and a boolean to check if the value has been set.
func (o *MultiselectFreetextOption) GetIsConfigurableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsConfigurable, true
}

// SetIsConfigurable sets field value
func (o *MultiselectFreetextOption) SetIsConfigurable(v bool) {
	o.IsConfigurable = v
}

// GetType returns the Type field value
func (o *MultiselectFreetextOption) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MultiselectFreetextOption) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MultiselectFreetextOption) SetType(v string) {
	o.Type = v
}

func (o MultiselectFreetextOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultiselectFreetextOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["available_options"] = o.AvailableOptions
	toSerialize["is_configurable"] = o.IsConfigurable
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *MultiselectFreetextOption) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
		"available_options",
		"is_configurable",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMultiselectFreetextOption := _MultiselectFreetextOption{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMultiselectFreetextOption)

	if err != nil {
		return err
	}

	*o = MultiselectFreetextOption(varMultiselectFreetextOption)

	return err
}

type NullableMultiselectFreetextOption struct {
	value *MultiselectFreetextOption
	isSet bool
}

func (v NullableMultiselectFreetextOption) Get() *MultiselectFreetextOption {
	return v.value
}

func (v *NullableMultiselectFreetextOption) Set(val *MultiselectFreetextOption) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiselectFreetextOption) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiselectFreetextOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiselectFreetextOption(val *MultiselectFreetextOption) *NullableMultiselectFreetextOption {
	return &NullableMultiselectFreetextOption{value: val, isSet: true}
}

func (v NullableMultiselectFreetextOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiselectFreetextOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


