/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnmapInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnmapInput{}

// UnmapInput UnmapInput
type UnmapInput struct {
	// The list of hosts to be unmapped
	HostMappings []string `json:"host_mappings"`
}

type _UnmapInput UnmapInput

// NewUnmapInput instantiates a new UnmapInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnmapInput(hostMappings []string) *UnmapInput {
	this := UnmapInput{}
	this.HostMappings = hostMappings
	return &this
}

// NewUnmapInputWithDefaults instantiates a new UnmapInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnmapInputWithDefaults() *UnmapInput {
	this := UnmapInput{}
	return &this
}

// GetHostMappings returns the HostMappings field value
func (o *UnmapInput) GetHostMappings() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.HostMappings
}

// GetHostMappingsOk returns a tuple with the HostMappings field value
// and a boolean to check if the value has been set.
func (o *UnmapInput) GetHostMappingsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HostMappings, true
}

// SetHostMappings sets field value
func (o *UnmapInput) SetHostMappings(v []string) {
	o.HostMappings = v
}

func (o UnmapInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnmapInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["host_mappings"] = o.HostMappings
	return toSerialize, nil
}

func (o *UnmapInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"host_mappings",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnmapInput := _UnmapInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnmapInput)

	if err != nil {
		return err
	}

	*o = UnmapInput(varUnmapInput)

	return err
}

type NullableUnmapInput struct {
	value *UnmapInput
	isSet bool
}

func (v NullableUnmapInput) Get() *UnmapInput {
	return v.value
}

func (v *NullableUnmapInput) Set(val *UnmapInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUnmapInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUnmapInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnmapInput(val *UnmapInput) *NullableUnmapInput {
	return &NullableUnmapInput{value: val, isSet: true}
}

func (v NullableUnmapInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnmapInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


