/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the UpdateMobilityGroupInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMobilityGroupInput{}

// UpdateMobilityGroupInput Input for update mobility group operation
type UpdateMobilityGroupInput struct {
	// Updated name of the mobility group
	Name *string `json:"name,omitempty"`
	// Updated description of the mobility group
	Description *string `json:"description,omitempty"`
	// Update the list of members (e.g. volumes).  This is the list of identifiers of members for the mobility group.  It will replace the current list of members.
	Members []string `json:"members,omitempty"`
}

// NewUpdateMobilityGroupInput instantiates a new UpdateMobilityGroupInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMobilityGroupInput() *UpdateMobilityGroupInput {
	this := UpdateMobilityGroupInput{}
	return &this
}

// NewUpdateMobilityGroupInputWithDefaults instantiates a new UpdateMobilityGroupInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMobilityGroupInputWithDefaults() *UpdateMobilityGroupInput {
	this := UpdateMobilityGroupInput{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateMobilityGroupInput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMobilityGroupInput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateMobilityGroupInput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateMobilityGroupInput) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateMobilityGroupInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMobilityGroupInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateMobilityGroupInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateMobilityGroupInput) SetDescription(v string) {
	o.Description = &v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *UpdateMobilityGroupInput) GetMembers() []string {
	if o == nil || IsNil(o.Members) {
		var ret []string
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMobilityGroupInput) GetMembersOk() ([]string, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *UpdateMobilityGroupInput) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []string and assigns it to the Members field.
func (o *UpdateMobilityGroupInput) SetMembers(v []string) {
	o.Members = v
}

func (o UpdateMobilityGroupInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMobilityGroupInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}
	return toSerialize, nil
}

type NullableUpdateMobilityGroupInput struct {
	value *UpdateMobilityGroupInput
	isSet bool
}

func (v NullableUpdateMobilityGroupInput) Get() *UpdateMobilityGroupInput {
	return v.value
}

func (v *NullableUpdateMobilityGroupInput) Set(val *UpdateMobilityGroupInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMobilityGroupInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMobilityGroupInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMobilityGroupInput(val *UpdateMobilityGroupInput) *NullableUpdateMobilityGroupInput {
	return &NullableUpdateMobilityGroupInput{value: val, isSet: true}
}

func (v NullableUpdateMobilityGroupInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMobilityGroupInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


