/*
APEX Orchestration Platform - Job Management System (JMS) API

Provides management and visibility for APEX Orchestration Platform Jobs

API version: IGNORED - see resource tag's x-api-version for the specific version of this resource.
Contact: apex.mars@dell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// ResourceTypeEnum Type of resource on which the job is operating. *OTHER_RESOURCE* is a special resource type value that allows referencing a instance from a different API suite by using the full resource URL suitable for GET as the resource_id value.
type ResourceTypeEnum string

// List of ResourceTypeEnum
const (
	RESOURCETYPEENUM_OTHER_RESOURCE ResourceTypeEnum = "OTHER_RESOURCE"
	RESOURCETYPEENUM_ALERTS ResourceTypeEnum = "alerts"
	RESOURCETYPEENUM_AUDIT_EVENTS ResourceTypeEnum = "audit-events"
	RESOURCETYPEENUM_BASIC_SYSTEM_INFO ResourceTypeEnum = "basic-system-info"
	RESOURCETYPEENUM_CERT_ROLE_MAPPINGS ResourceTypeEnum = "cert-role-mappings"
	RESOURCETYPEENUM_CERT_LOCAL_ACCOUNT_MAPPINGS ResourceTypeEnum = "cert-local-account-mappings"
	RESOURCETYPEENUM_DNS_CONFIG ResourceTypeEnum = "dns-config"
	RESOURCETYPEENUM_EVENTS ResourceTypeEnum = "events"
	RESOURCETYPEENUM_FEDERATED_ELEMENTS ResourceTypeEnum = "federated-elements"
	RESOURCETYPEENUM_INITIAL_CONFIG ResourceTypeEnum = "initial-config"
	RESOURCETYPEENUM_JOBS ResourceTypeEnum = "jobs"
	RESOURCETYPEENUM_KMIP_SERVICES ResourceTypeEnum = "kmip-services"
	RESOURCETYPEENUM_LDAPS ResourceTypeEnum = "ldaps"
	RESOURCETYPEENUM_LDAP_ROLE_MAPPINGS ResourceTypeEnum = "ldap-role-mappings"
	RESOURCETYPEENUM_LICENSES ResourceTypeEnum = "licenses"
	RESOURCETYPEENUM_LICENSES_CONFIG ResourceTypeEnum = "licenses-config"
	RESOURCETYPEENUM_LOCAL_ACCOUNTS ResourceTypeEnum = "local-accounts"
	RESOURCETYPEENUM_LOCAL_ACCOUNTS_CONFIG ResourceTypeEnum = "local-accounts-config"
	RESOURCETYPEENUM_LOGIN ResourceTypeEnum = "login"
	RESOURCETYPEENUM_METRIC_METADATA ResourceTypeEnum = "metric-metadata"
	RESOURCETYPEENUM_METRICS ResourceTypeEnum = "metrics"
	RESOURCETYPEENUM_MFA_CACPIVS ResourceTypeEnum = "mfa-cacpivs"
	RESOURCETYPEENUM_MFA_SECURIDS ResourceTypeEnum = "mfa-securids"
	RESOURCETYPEENUM_OAUTH2_SERVICES ResourceTypeEnum = "oauth2-services"
	RESOURCETYPEENUM_OIDC_SERVICES ResourceTypeEnum = "oidc-services"
	RESOURCETYPEENUM_RESOURCE_TAGS ResourceTypeEnum = "resource-tags"
	RESOURCETYPEENUM_ROLES ResourceTypeEnum = "roles"
	RESOURCETYPEENUM_SAML_SERVICES ResourceTypeEnum = "saml-services"
	RESOURCETYPEENUM_SCV ResourceTypeEnum = "scv"
	RESOURCETYPEENUM_SECURITY_CONFIG ResourceTypeEnum = "security-config"
	RESOURCETYPEENUM_SMTP_SERVICES ResourceTypeEnum = "smtp-services"
	RESOURCETYPEENUM_SMTP_EMAIL_SUBSCRIPTIONS ResourceTypeEnum = "smtp-email-subscriptions"
	RESOURCETYPEENUM_SNMP_SERVICES ResourceTypeEnum = "snmp-services"
	RESOURCETYPEENUM_SNMP_TRAP_SUBSCRIPTIONS ResourceTypeEnum = "snmp-trap-subscriptions"
	RESOURCETYPEENUM_SOFTWARE_PACKAGES ResourceTypeEnum = "software-packages"
	RESOURCETYPEENUM_SUPPORT_CONNECTIVITY_CONFIG ResourceTypeEnum = "support-connectivity-config"
	RESOURCETYPEENUM_SUPPORT_CUSTOMER_CONTACTS ResourceTypeEnum = "support-customer-contacts"
	RESOURCETYPEENUM_SUPPORT_MATERIALS ResourceTypeEnum = "support-materials"
	RESOURCETYPEENUM_SYSLOGS ResourceTypeEnum = "syslogs"
	RESOURCETYPEENUM_SYSLOG_SUBSCRIPTIONS ResourceTypeEnum = "syslog-subscriptions"
	RESOURCETYPEENUM_TAGS ResourceTypeEnum = "tags"
	RESOURCETYPEENUM_TIME_CONFIG ResourceTypeEnum = "time-config"
	RESOURCETYPEENUM_WEBHOOK_TARGETS ResourceTypeEnum = "webhook-targets"
	RESOURCETYPEENUM_WEBHOOK_SUBSCRIPTIONS ResourceTypeEnum = "webhook-subscriptions"
	RESOURCETYPEENUM_WEBHOOK_MESSAGES ResourceTypeEnum = "webhook-messages"
	RESOURCETYPEENUM_X509_CERTIFICATES ResourceTypeEnum = "x509-certificates"
	RESOURCETYPEENUM_AWS_ACCOUNTS ResourceTypeEnum = "aws-accounts"
	RESOURCETYPEENUM_AWS_PERMISSION_POLICIES ResourceTypeEnum = "aws-permission-policies"
	RESOURCETYPEENUM_STORAGE_PRODUCTS ResourceTypeEnum = "storage-products"
	RESOURCETYPEENUM_STORAGE_PRODUCT_OPTIONS ResourceTypeEnum = "storage-product-options"
	RESOURCETYPEENUM_MOBILITY_TARGETS ResourceTypeEnum = "mobility-targets"
	RESOURCETYPEENUM_MOBILITY_GROUPS ResourceTypeEnum = "mobility-groups"
	RESOURCETYPEENUM_CLONES ResourceTypeEnum = "clones"
	RESOURCETYPEENUM_STORAGE_SYSTEM_TOKENS ResourceTypeEnum = "storage-system-tokens"
	RESOURCETYPEENUM_STORAGE_SYSTEMS ResourceTypeEnum = "storage-systems"
)

// All allowed values of ResourceTypeEnum enum
var AllowedResourceTypeEnumEnumValues = []ResourceTypeEnum{
	"OTHER_RESOURCE",
	"alerts",
	"audit-events",
	"basic-system-info",
	"cert-role-mappings",
	"cert-local-account-mappings",
	"dns-config",
	"events",
	"federated-elements",
	"initial-config",
	"jobs",
	"kmip-services",
	"ldaps",
	"ldap-role-mappings",
	"licenses",
	"licenses-config",
	"local-accounts",
	"local-accounts-config",
	"login",
	"metric-metadata",
	"metrics",
	"mfa-cacpivs",
	"mfa-securids",
	"oauth2-services",
	"oidc-services",
	"resource-tags",
	"roles",
	"saml-services",
	"scv",
	"security-config",
	"smtp-services",
	"smtp-email-subscriptions",
	"snmp-services",
	"snmp-trap-subscriptions",
	"software-packages",
	"support-connectivity-config",
	"support-customer-contacts",
	"support-materials",
	"syslogs",
	"syslog-subscriptions",
	"tags",
	"time-config",
	"webhook-targets",
	"webhook-subscriptions",
	"webhook-messages",
	"x509-certificates",
	"aws-accounts",
	"aws-permission-policies",
	"storage-products",
	"storage-product-options",
	"mobility-targets",
	"mobility-groups",
	"clones",
	"storage-system-tokens",
	"storage-systems",
}

func (v *ResourceTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ResourceTypeEnum(value)
	for _, existing := range AllowedResourceTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ResourceTypeEnum", value)
}

// NewResourceTypeEnumFromValue returns a pointer to a valid ResourceTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewResourceTypeEnumFromValue(v string) (*ResourceTypeEnum, error) {
	ev := ResourceTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ResourceTypeEnum: valid values are %v", v, AllowedResourceTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ResourceTypeEnum) IsValid() bool {
	for _, existing := range AllowedResourceTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ResourceTypeEnum value
func (v ResourceTypeEnum) Ptr() *ResourceTypeEnum {
	return &v
}

type NullableResourceTypeEnum struct {
	value *ResourceTypeEnum
	isSet bool
}

func (v NullableResourceTypeEnum) Get() *ResourceTypeEnum {
	return v.value
}

func (v *NullableResourceTypeEnum) Set(val *ResourceTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceTypeEnum(val *ResourceTypeEnum) *NullableResourceTypeEnum {
	return &NullableResourceTypeEnum{value: val, isSet: true}
}

func (v NullableResourceTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

