set APEX_SAML_TOKEN_SCRIPT_DIR="/my/dirpath"
set APEX_SAML_TOKEN_SCRIPT_NAME="saml_get_token.py"
set APEX_SAML_TOKEN_OUTPUT_FILE_NAME="\tmp\samlPipe"
set APEX_DI_TOKEN_URL="https://www-example.com/oauth/token"
set APEX_TOKEN_ACCESS_KEY="aaa-bbb-ccc"
set APEX_TOKEN_SECRET="random"