/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the MobilityGroupsCollection200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MobilityGroupsCollection200Response{}

// MobilityGroupsCollection200Response struct for MobilityGroupsCollection200Response
type MobilityGroupsCollection200Response struct {
	Results []MobilityGroup `json:"results,omitempty"`
}

// NewMobilityGroupsCollection200Response instantiates a new MobilityGroupsCollection200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMobilityGroupsCollection200Response() *MobilityGroupsCollection200Response {
	this := MobilityGroupsCollection200Response{}
	return &this
}

// NewMobilityGroupsCollection200ResponseWithDefaults instantiates a new MobilityGroupsCollection200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMobilityGroupsCollection200ResponseWithDefaults() *MobilityGroupsCollection200Response {
	this := MobilityGroupsCollection200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *MobilityGroupsCollection200Response) GetResults() []MobilityGroup {
	if o == nil || IsNil(o.Results) {
		var ret []MobilityGroup
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MobilityGroupsCollection200Response) GetResultsOk() ([]MobilityGroup, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *MobilityGroupsCollection200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []MobilityGroup and assigns it to the Results field.
func (o *MobilityGroupsCollection200Response) SetResults(v []MobilityGroup) {
	o.Results = v
}

func (o MobilityGroupsCollection200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MobilityGroupsCollection200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableMobilityGroupsCollection200Response struct {
	value *MobilityGroupsCollection200Response
	isSet bool
}

func (v NullableMobilityGroupsCollection200Response) Get() *MobilityGroupsCollection200Response {
	return v.value
}

func (v *NullableMobilityGroupsCollection200Response) Set(val *MobilityGroupsCollection200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableMobilityGroupsCollection200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableMobilityGroupsCollection200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMobilityGroupsCollection200Response(val *MobilityGroupsCollection200Response) *NullableMobilityGroupsCollection200Response {
	return &NullableMobilityGroupsCollection200Response{value: val, isSet: true}
}

func (v NullableMobilityGroupsCollection200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMobilityGroupsCollection200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


