/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CloneCreateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloneCreateInput{}

// CloneCreateInput Entity that will be passed on to create a clone
type CloneCreateInput struct {
	// Name of this clone group
	Name string `json:"name"`
	// Description of this clone group
	Description *string `json:"description,omitempty"`
	// ID of the mobility target that was used to create the clone
	MobilityTargetId string `json:"mobility_target_id"`
	// IDs of hosts that this clone should be exposed to
	HostMappings []string `json:"host_mappings,omitempty"`
}

type _CloneCreateInput CloneCreateInput

// NewCloneCreateInput instantiates a new CloneCreateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloneCreateInput(name string, mobilityTargetId string) *CloneCreateInput {
	this := CloneCreateInput{}
	this.Name = name
	this.MobilityTargetId = mobilityTargetId
	return &this
}

// NewCloneCreateInputWithDefaults instantiates a new CloneCreateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloneCreateInputWithDefaults() *CloneCreateInput {
	this := CloneCreateInput{}
	return &this
}

// GetName returns the Name field value
func (o *CloneCreateInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CloneCreateInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CloneCreateInput) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CloneCreateInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloneCreateInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CloneCreateInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CloneCreateInput) SetDescription(v string) {
	o.Description = &v
}

// GetMobilityTargetId returns the MobilityTargetId field value
func (o *CloneCreateInput) GetMobilityTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MobilityTargetId
}

// GetMobilityTargetIdOk returns a tuple with the MobilityTargetId field value
// and a boolean to check if the value has been set.
func (o *CloneCreateInput) GetMobilityTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MobilityTargetId, true
}

// SetMobilityTargetId sets field value
func (o *CloneCreateInput) SetMobilityTargetId(v string) {
	o.MobilityTargetId = v
}

// GetHostMappings returns the HostMappings field value if set, zero value otherwise.
func (o *CloneCreateInput) GetHostMappings() []string {
	if o == nil || IsNil(o.HostMappings) {
		var ret []string
		return ret
	}
	return o.HostMappings
}

// GetHostMappingsOk returns a tuple with the HostMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloneCreateInput) GetHostMappingsOk() ([]string, bool) {
	if o == nil || IsNil(o.HostMappings) {
		return nil, false
	}
	return o.HostMappings, true
}

// HasHostMappings returns a boolean if a field has been set.
func (o *CloneCreateInput) HasHostMappings() bool {
	if o != nil && !IsNil(o.HostMappings) {
		return true
	}

	return false
}

// SetHostMappings gets a reference to the given []string and assigns it to the HostMappings field.
func (o *CloneCreateInput) SetHostMappings(v []string) {
	o.HostMappings = v
}

func (o CloneCreateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloneCreateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["mobility_target_id"] = o.MobilityTargetId
	if !IsNil(o.HostMappings) {
		toSerialize["host_mappings"] = o.HostMappings
	}
	return toSerialize, nil
}

func (o *CloneCreateInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"mobility_target_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloneCreateInput := _CloneCreateInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCloneCreateInput)

	if err != nil {
		return err
	}

	*o = CloneCreateInput(varCloneCreateInput)

	return err
}

type NullableCloneCreateInput struct {
	value *CloneCreateInput
	isSet bool
}

func (v NullableCloneCreateInput) Get() *CloneCreateInput {
	return v.value
}

func (v *NullableCloneCreateInput) Set(val *CloneCreateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCloneCreateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCloneCreateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloneCreateInput(val *CloneCreateInput) *NullableCloneCreateInput {
	return &NullableCloneCreateInput{value: val, isSet: true}
}

func (v NullableCloneCreateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloneCreateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


