/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the AwsPermissionPoliciesCollection200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsPermissionPoliciesCollection200Response{}

// AwsPermissionPoliciesCollection200Response struct for AwsPermissionPoliciesCollection200Response
type AwsPermissionPoliciesCollection200Response struct {
	Results []AwsPermissionPoliciesInstance `json:"results,omitempty"`
}

// NewAwsPermissionPoliciesCollection200Response instantiates a new AwsPermissionPoliciesCollection200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsPermissionPoliciesCollection200Response() *AwsPermissionPoliciesCollection200Response {
	this := AwsPermissionPoliciesCollection200Response{}
	return &this
}

// NewAwsPermissionPoliciesCollection200ResponseWithDefaults instantiates a new AwsPermissionPoliciesCollection200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsPermissionPoliciesCollection200ResponseWithDefaults() *AwsPermissionPoliciesCollection200Response {
	this := AwsPermissionPoliciesCollection200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *AwsPermissionPoliciesCollection200Response) GetResults() []AwsPermissionPoliciesInstance {
	if o == nil || IsNil(o.Results) {
		var ret []AwsPermissionPoliciesInstance
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsPermissionPoliciesCollection200Response) GetResultsOk() ([]AwsPermissionPoliciesInstance, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *AwsPermissionPoliciesCollection200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []AwsPermissionPoliciesInstance and assigns it to the Results field.
func (o *AwsPermissionPoliciesCollection200Response) SetResults(v []AwsPermissionPoliciesInstance) {
	o.Results = v
}

func (o AwsPermissionPoliciesCollection200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsPermissionPoliciesCollection200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableAwsPermissionPoliciesCollection200Response struct {
	value *AwsPermissionPoliciesCollection200Response
	isSet bool
}

func (v NullableAwsPermissionPoliciesCollection200Response) Get() *AwsPermissionPoliciesCollection200Response {
	return v.value
}

func (v *NullableAwsPermissionPoliciesCollection200Response) Set(val *AwsPermissionPoliciesCollection200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsPermissionPoliciesCollection200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsPermissionPoliciesCollection200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsPermissionPoliciesCollection200Response(val *AwsPermissionPoliciesCollection200Response) *NullableAwsPermissionPoliciesCollection200Response {
	return &NullableAwsPermissionPoliciesCollection200Response{value: val, isSet: true}
}

func (v NullableAwsPermissionPoliciesCollection200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsPermissionPoliciesCollection200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


