/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the StorageSystemsCollection200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageSystemsCollection200Response{}

// StorageSystemsCollection200Response struct for StorageSystemsCollection200Response
type StorageSystemsCollection200Response struct {
	Results []StorageSystemsInstance `json:"results,omitempty"`
}

// NewStorageSystemsCollection200Response instantiates a new StorageSystemsCollection200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageSystemsCollection200Response() *StorageSystemsCollection200Response {
	this := StorageSystemsCollection200Response{}
	return &this
}

// NewStorageSystemsCollection200ResponseWithDefaults instantiates a new StorageSystemsCollection200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageSystemsCollection200ResponseWithDefaults() *StorageSystemsCollection200Response {
	this := StorageSystemsCollection200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *StorageSystemsCollection200Response) GetResults() []StorageSystemsInstance {
	if o == nil || IsNil(o.Results) {
		var ret []StorageSystemsInstance
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageSystemsCollection200Response) GetResultsOk() ([]StorageSystemsInstance, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *StorageSystemsCollection200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []StorageSystemsInstance and assigns it to the Results field.
func (o *StorageSystemsCollection200Response) SetResults(v []StorageSystemsInstance) {
	o.Results = v
}

func (o StorageSystemsCollection200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageSystemsCollection200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableStorageSystemsCollection200Response struct {
	value *StorageSystemsCollection200Response
	isSet bool
}

func (v NullableStorageSystemsCollection200Response) Get() *StorageSystemsCollection200Response {
	return v.value
}

func (v *NullableStorageSystemsCollection200Response) Set(val *StorageSystemsCollection200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageSystemsCollection200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageSystemsCollection200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageSystemsCollection200Response(val *StorageSystemsCollection200Response) *NullableStorageSystemsCollection200Response {
	return &NullableStorageSystemsCollection200Response{value: val, isSet: true}
}

func (v NullableStorageSystemsCollection200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageSystemsCollection200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


