/*
APEX Navigator for Multicloud Storage REST APIs

The public API definitions for APEX Navigator for Multicloud Storage

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the AwsAccountsCollection200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsAccountsCollection200Response{}

// AwsAccountsCollection200Response struct for AwsAccountsCollection200Response
type AwsAccountsCollection200Response struct {
	Results []RedactedAwsAccountInstance `json:"results,omitempty"`
}

// NewAwsAccountsCollection200Response instantiates a new AwsAccountsCollection200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsAccountsCollection200Response() *AwsAccountsCollection200Response {
	this := AwsAccountsCollection200Response{}
	return &this
}

// NewAwsAccountsCollection200ResponseWithDefaults instantiates a new AwsAccountsCollection200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsAccountsCollection200ResponseWithDefaults() *AwsAccountsCollection200Response {
	this := AwsAccountsCollection200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *AwsAccountsCollection200Response) GetResults() []RedactedAwsAccountInstance {
	if o == nil || IsNil(o.Results) {
		var ret []RedactedAwsAccountInstance
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsAccountsCollection200Response) GetResultsOk() ([]RedactedAwsAccountInstance, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *AwsAccountsCollection200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []RedactedAwsAccountInstance and assigns it to the Results field.
func (o *AwsAccountsCollection200Response) SetResults(v []RedactedAwsAccountInstance) {
	o.Results = v
}

func (o AwsAccountsCollection200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsAccountsCollection200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableAwsAccountsCollection200Response struct {
	value *AwsAccountsCollection200Response
	isSet bool
}

func (v NullableAwsAccountsCollection200Response) Get() *AwsAccountsCollection200Response {
	return v.value
}

func (v *NullableAwsAccountsCollection200Response) Set(val *AwsAccountsCollection200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsAccountsCollection200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsAccountsCollection200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsAccountsCollection200Response(val *AwsAccountsCollection200Response) *NullableAwsAccountsCollection200Response {
	return &NullableAwsAccountsCollection200Response{value: val, isSet: true}
}

func (v NullableAwsAccountsCollection200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsAccountsCollection200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


